name: Pull request and develop checks

on:
  pull_request:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
